name: Create release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish_docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_ALIYUN_REGISTRY }}
          username: ${{ secrets.DOCKER_ALIYUN_USERNAME }}
          password: ${{ secrets.DOCKER_ALIYUN_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            yinheli/duckdb:latest
            yinheli/duckdb:${{ github.ref_name }}
            ${{ secrets.DOCKER_ALIYUN_REGISTRY }}/rshenry/duckdb:latest
            ${{ secrets.DOCKER_ALIYUN_REGISTRY }}/rshenry/duckdb:${{ github.ref_name }}
