name: Create release and upload binaries

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"

permissions:
  contents: write

jobs:
  publish_docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            yinheli/duckdb:latest
            yinheli/duckdb:${{ github.ref_name }}